[versions]
clikt = "5.1.0"
junit = "5.14.3"
kotlin = "2.3.10"
kotlin-logging-jvm = "7.0.14"
ktfmt = "0.21.0"
slf4j = "2.0.17"
test-logger = "4.0.0"

[libraries]
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

[plugins]
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref= "ktfmt"}
